Current location bug
Medology/findalab pull request #327
Opened 2021-07-13 22:48 UTC by gamanuel

For: https://github.com/Medology/www.utitreatment.com/issues/1244

FEATURE IMPLEMENTATION: When a user clicked on `use current locations` and doesn't allow the browser to read the locations, then if the user clicks a lab/pharmacies that was loaded after that action it will throw an error.

Without conditional:
<img width="1304" alt="Screen Shot 2021-07-13 at 19 23 24" src="https://user-images.githubusercontent.com/42519487/125532886-7f2410e4-2d1e-4abb-bb6d-563d29def238.png">

With conditional:
<img width="1243" alt="Screen Shot 2021-07-13 at 19 26 35" src="https://user-images.githubusercontent.com/42519487/125533144-8b6d70be-4fa7-4f16-8272-11b364978e2e.png">

2021-07-13 22:49 UTC, gamanuel commented
First commit is the style fixer

2021-07-14 13:52 UTC, izazueta approved these changes

2021-07-14 14:40 UTC, fortoulrodolfo requested changes

2021-07-14 14:40 UTC, fortoulrodolfo commented on src/js/findalab.js
> +          if (labDiv.position()) {
its better if you use a guard instead of placing all the code inside the if.

maybe you can do something like this:

```
if (labDiv.position() == undefined) {
  return;
}
```

Guards are easier to read and checking for a code inside the if conditional. What do you think?

2021-07-14 14:58 UTC, gamanuel commented on src/js/findalab.js
> +          if (labDiv.position()) {
Yes, totally agree

2021-07-14 17:32 UTC, johnnie502 approved these changes

2021-07-14 22:13 UTC, fortoulrodolfo approved these changes

2021-07-16 11:07 UTC, merged